name: android-aarch64-wheel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cross-rs/aarch64-linux-android:main
    steps:
      - uses: actions/checkout@v4

      - name: Install Python & maturin
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends python3 python3-pip python3-venv curl
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip maturin
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
          rustup target add aarch64-linux-android

      - name: Build uv wheel (Android aarch64)
        run: |
          . venv/bin/activate
          maturin build --release \
            --target aarch64-linux-android \
            --compatibility off \
            -o dist

      - uses: actions/upload-artifact@v4
        with:
          name: uv-android-wheel
          path: dist/*.whl
